kind: HorizontalpodAutoscaler
apiVersion: autoscaling/v2
metadata:
  name: apache-hpa
  namespace: apache-ns
spec:
  scaleTargetRef:
    kind: Deployment
    apiVersion: apps/v1
    name: apache-dep
minReplicas: 1
maxReplicas: 5
matrics:
  -type: Resources
     resource:
       name: cpu
       target:
         - type: Utilization
           averageUtilization: 5


