apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: apache-rolebinding
  namespace: apache-ns
subjects:
- kind: User
  name: apache-user1
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  apiGroup: rbac.authorization.k8s.io
  name: apache-manager
