apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: apache-role-manager
  namespace: apache-ns
rules:
  - apiGroups: ["", "app", "rbac.authorization.k8s.io", "batch"]   
    resources: ["pod","deployment","service"]
    verbs: ["get", "apply", "delete", "watch", "create", "patch"]
