apiVersion: v1
kind: Service
metadata:
  name: apache-service
  namespace: apache-ns
spec:
  selector:
    app: apache-label
  ports:
    - protocol: TCP
      port: 80  #exposed port in the cluster
      targetPort: 80 # container port
