kind: VerticalPodAutoscaler
apiVersion: autoscaling.k8s.io/v1
metadata:
  name: apache-vpa
  namespace: apache-ns
spec:
  targetRef:             #scaleTargetRef in hpa
    name: apache-dep
    kind: Deployment
    apiVersion: apps/v1
  updatePolicy:
    updateMode: "Auto"
  
