kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: surya-pvc
  namespace: surya-ns
  labels:
    app: surya-pvc-label
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-storage
