kind: PersistentVolume
apiVersion: v1
metadata:
  name: surya-pv
  labels:
    app: surya-pv-label
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
    path: /mnt/data
